# Generated by Django 6.1 on 2026-09-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cicloproduccion',
            old_name='fecha_fin',
            new_name='fecha_fin_estimada',
        ),

        migrations.RenameField(
            model_name='cultivo',
            old_name='fecha_inicio',
            new_name='fecha_creacion',
        ),

        migrations.RenameField(
            model_name='cicloproduccion',
            old_name='id',
            new_name='id_ciclo',
        ),

        migrations.RenameField(
            model_name='cultivo',
            old_name='id',
            new_name='id_cultivo',
        ),

        migrations.RemoveField(
            model_name='cicloproduccion',
            name='activo',
        ),

        migrations.RemoveField(
            model_name='cultivo',
            name='activo',
        ),

        migrations.RemoveField(
            model_name='cultivo',
            name='descripcion',
        ),

        migrations.AddField(
            model_name='cicloproduccion',
            name='estado',
            field=models.CharField(
                default='germinacion',
                max_length=30,
            ),
        ),

        migrations.AddField(
            model_name='cicloproduccion',
            name='fecha_fin_real',
            field=models.DateField(
                blank=True,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name='cultivo',
            name='tipo_cultivo',
            field=models.CharField(
                default='No especificado',
                max_length=100,
            ),
        ),
    ]