# Generated by Django 6.1 on 2026-09-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0002_rename_fecha_fin_cicloproduccion_fecha_fin_estimada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cicloproduccion',
            name='id_ciclo',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='id_cultivo',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
