# Generated by Django 6.1 on 2026-09-26 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivos', '0003_alter_cicloproduccion_id_ciclo_and_more'),
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='analisis/%Y/%m/%d/')),
                ('fecha_hora', models.DateTimeField(help_text='Momento real de la captura en el dispositivo.')),
                ('origen_captura', models.CharField(choices=[('periodica', 'Periódica'), ('evento', 'Por evento'), ('manual', 'Manual'), ('sync_sd', 'Sincronizada desde SD')], default='periodica', max_length=20)),
                ('hash_sha256', models.CharField(blank=True, db_index=True, help_text='Para evitar duplicados al sincronizar desde SD.', max_length=64)),
                ('altura_estimada_cm', models.FloatField(blank=True, null=True)),
                ('area_foliar_cm2', models.FloatField(blank=True, null=True)),
                ('indice_verdor', models.FloatField(blank=True, null=True)),
                ('cobertura_pct', models.FloatField(blank=True, null=True)),
                ('delta_altura_cm', models.FloatField(blank=True, null=True)),
                ('confianza', models.FloatField(default=0.0, help_text='0.0 a 1.0')),
                ('etapa_fenologica', models.CharField(choices=[('germinacion', 'Germinación'), ('plantula', 'Plántula'), ('crecimiento', 'Crecimiento vegetativo'), ('floracion', 'Floración'), ('cosecha', 'Cosecha')], default='germinacion', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('procesada', models.BooleanField(db_index=True, default=False, help_text='True cuando el análisis automático ya corrió sobre esta imagen.')),
                ('error_analisis', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Cuándo llegó la imagen al backend (puede diferir de la captura).')),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis_imagen', to='cultivos.cicloproduccion')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_imagen', to='cultivos.cultivo')),
                ('dispositivo', models.ForeignKey(blank=True, help_text='Cámara que tomó la foto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis_imagen', to='dispositivos.dispositivo')),
            ],
            options={
                'verbose_name': 'Análisis de imagen',
                'verbose_name_plural': 'Análisis de imágenes',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='AvisoCrecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sin_crecimiento', 'Sin crecimiento'), ('crecimiento_negativo', 'Crecimiento negativo'), ('desvio_curva', 'Desvío respecto a la curva esperada'), ('caida_verdor', 'Caída del índice de verdor')], max_length=30)),
                ('severidad', models.CharField(choices=[('info', 'Información'), ('advertencia', 'Advertencia')], default='info', max_length=15)),
                ('descripcion', models.TextField()),
                ('resuelto', models.BooleanField(db_index=True, default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('analisis_origen', models.ForeignKey(blank=True, help_text='SET_NULL para que borrar imágenes viejas no borre avisos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos', to='inteligencia.analisisimagen')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_crecimiento', to='cultivos.cultivo')),
            ],
            options={
                'verbose_name': 'Aviso de crecimiento',
                'verbose_name_plural': 'Avisos de crecimiento',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ParametroImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia_captura_minutos', models.PositiveIntegerField(default=30, help_text='Intervalo entre capturas periódicas, en minutos.')),
                ('hora_inicio_captura', models.PositiveSmallIntegerField(default=8, help_text='Hora (0-23) a partir de la cual se capturan imágenes.')),
                ('hora_fin_captura', models.PositiveSmallIntegerField(default=19, help_text='Hora (0-23) hasta la cual se capturan imágenes.')),
                ('capturar_por_evento', models.BooleanField(default=True, help_text='Capturar una imagen adicional cuando ocurre una alerta o evento.')),
                ('retencion_dias', models.PositiveIntegerField(default=7, help_text='Días de historial de imágenes a conservar en el backend.')),
                ('distancia_camara_cm', models.FloatField(default=30.0)),
                ('marcador_referencia_cm', models.FloatField(blank=True, help_text='Tamaño real del objeto de referencia (regla, sticker, ArUco).', null=True)),
                ('pixeles_por_cm', models.FloatField(blank=True, help_text='Factor de conversión píxel→cm.', null=True)),
                ('dias_sin_crecimiento_para_aviso', models.PositiveIntegerField(default=3)),
                ('desvio_maximo_curva_pct', models.FloatField(default=25.0)),
                ('caida_verdor_pct_para_aviso', models.FloatField(default=20.0)),
                ('curva_esperada', models.JSONField(blank=True, default=dict, help_text="Ej: {'crecimiento': [[13, 6], [35, 25]]}.")),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cultivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametro_imagen', to='cultivos.cultivo')),
            ],
            options={
                'verbose_name': 'Parámetro de imagen',
                'verbose_name_plural': 'Parámetros de imagen',
            },
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('riego', 'Riego'), ('nutricion', 'Nutrición'), ('ph', 'Ajuste de pH'), ('conductividad', 'Ajuste de conductividad'), ('temperatura', 'Temperatura'), ('iluminacion', 'Iluminación'), ('crecimiento', 'Crecimiento'), ('cosecha', 'Cosecha'), ('otro', 'Otro')], max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('detalle', models.TextField(blank=True)),
                ('regla_origen', models.CharField(help_text="Identificador de la regla que la generó. Ej: 'ph_bajo_sostenido'.", max_length=100)),
                ('vigente', models.BooleanField(db_index=True, default=True)),
                ('resuelta', models.BooleanField(db_index=True, default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='cultivos.cultivo')),
            ],
            options={
                'verbose_name': 'Recomendación',
                'verbose_name_plural': 'Recomendaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='analisisimagen',
            index=models.Index(fields=['cultivo', '-fecha_hora'], name='inteligenci_cultivo_75c8c3_idx'),
        ),
        migrations.AddIndex(
            model_name='analisisimagen',
            index=models.Index(fields=['dispositivo', '-fecha_hora'], name='inteligenci_disposi_14e536_idx'),
        ),
        migrations.AddIndex(
            model_name='recomendacion',
            index=models.Index(fields=['cultivo', '-fecha'], name='inteligenci_cultivo_5b928c_idx'),
        ),
        migrations.AddIndex(
            model_name='recomendacion',
            index=models.Index(fields=['vigente', 'resuelta'], name='inteligenci_vigente_48c983_idx'),
        ),
    ]
