# Generated by Django 6.1 on 2026-10-01 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0003_alter_cicloproduccion_id_ciclo_and_more'),
        ('inteligencia', '0001_initial'),
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('medicion', 'Medición individual'), ('tendencia', 'Tendencia en ventana'), ('imagen', 'Análisis de imagen')], default='medicion', max_length=15)),
                ('score', models.FloatField(help_text='Score del Isolation Forest. Mayor = más anómalo.')),
                ('valor_observado', models.FloatField()),
                ('valor_esperado_min', models.FloatField(blank=True, null=True)),
                ('valor_esperado_max', models.FloatField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('modelo_version', models.CharField(default='iforest-v1', help_text='Versión del modelo que generó la detección.', max_length=20)),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('revisada', 'Revisada'), ('descartada', 'Descartada')], default='nueva', max_length=15)),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalias', to='cultivos.cultivo')),
                ('medicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalias', to='monitoreo.medicion')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalias', to='monitoreo.sensor')),
            ],
            options={
                'verbose_name': 'Anomalía',
                'verbose_name_plural': 'Anomalías',
                'ordering': ['-fecha_deteccion'],
                'indexes': [models.Index(fields=['cultivo', '-fecha_deteccion'], name='inteligenci_cultivo_ce5a87_idx'), models.Index(fields=['estado'], name='inteligenci_estado_aca824_idx'), models.Index(fields=['sensor', '-fecha_deteccion'], name='inteligenci_sensor__e17297_idx')],
            },
        ),
    ]
