# Generated by Django 6.1 on 2026-09-11 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_maximo_sin_lectura', models.DurationField()),
                ('lecturas_consecutivas_apertura', models.PositiveSmallIntegerField(default=3)),
                ('lecturas_consecutivas_cierre', models.PositiveSmallIntegerField(default=3)),
                ('umbral_desviacion_alta', models.FloatField()),
                ('valor_umbral_alerta', models.FloatField(blank=True, null=True)),
                ('tipo_sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametro_alerta', to='monitoreo.tiposensor')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=10)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('resuelta', 'Resuelta')], default='activa', max_length=10)),
                ('fecha_hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='eventos.evento')),
                ('medicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='monitoreo.medicion')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('evento__isnull', True), ('medicion__isnull', False)), models.Q(('evento__isnull', False), ('medicion__isnull', True)), _connector='OR'), name='alerta_origen_exclusivo')],
            },
        ),
    ]
