# Generated by Django 6.1 on 2026-09-27 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivos', '0003_alter_cicloproduccion_id_ciclo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('monitoreo', 'Monitoreo de sensores'), ('alertas', 'Historial de alertas'), ('eventos', 'Historial de eventos'), ('crecimiento', 'Crecimiento del cultivo'), ('intervenciones', 'Intervenciones'), ('recomendaciones', 'Recomendaciones')], max_length=20)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=5)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/%Y/%m/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('generando', 'Generando'), ('listo', 'Listo'), ('error', 'Error')], default='pendiente', max_length=10)),
                ('error_detalle', models.TextField(blank=True)),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_generacion', models.DateTimeField(blank=True, null=True)),
                ('cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='cultivos.cultivo')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
