# Generated by Django 6.1 on 2026-09-11 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivos', '0003_alter_cicloproduccion_id_ciclo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_dispositivo', models.CharField(choices=[('sensor', 'Sensor'), ('bomba', 'Bomba'), ('otro', 'Otro')], max_length=20)),
                ('identificador_hardware', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='cultivos.cultivo')),
            ],
        ),
    ]
