# Generated by Django 6.1 on 2026-09-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='api_key_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='ip_local',
            field=models.GenericIPAddressField(blank=True, help_text='IP del ESP32 en la red local. Ej: 192.168.1.50', null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='permite_polling',
            field=models.BooleanField(default=False, help_text='Si es True, el servidor le pide fotos al dispositivo periódicamente.'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='url_captura',
            field=models.URLField(blank=True, help_text='URL completa de captura. Si se completa, tiene prioridad sobre ip_local.'),
        ),
    ]
